name: uas_pemrograman_aplikasi_bergerak
description: "UAS Pemrograman Aplikasi Bergerak"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#1A7F7A"
    theme_color: "#F5F5F1"
  windows:
    generate: false
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: false
    image_path: "assets/icon.png"
